package org.boesenet;

import org.boesenet.serialization.SerializationUtil;
import org.junit.Test;

import java.util.function.Predicate;

import static org.junit.Assert.assertNotNull;

public class SerializationUtilTest {

    private static final String serializedPredicate = "rO0ABXNyADVvcmcuYm9lc2VuZXQucHJlZGljYXRlLm9wZXJhdGlvbnMuTG9naWNhbEFuZE9wZXJhdGlvbjQmWez3ekdTAgACTAAMbGVmdEhhbmRTaWRldAAeTGphdmEvdXRpbC9mdW5jdGlvbi9QcmVkaWNhdGU7TAANcmlnaHRIYW5kU2lkZXEAfgABeHBzcgA0b3JnLmJvZXNlbmV0LnByZWRpY2F0ZS5vcGVyYXRpb25zLkxvZ2ljYWxPck9wZXJhdGlvbqN6IbpEj00GAgACTAAMbGVmdEhhbmRTaWRlcQB+AAFMAA1yaWdodEhhbmRTaWRlcQB+AAF4cHNxAH4AA3NyADVvcmcuYm9lc2VuZXQucHJlZGljYXRlLm9wZXJhdGlvbnMuSHR0cE1ldGhvZFByZWRpY2F0ZQ3hrImODWszAgABTAAGbWV0aG9kdAAZTG9yZy9ib2VzZW5ldC9IdHRwTWV0aG9kO3hwfnIAF29yZy5ib2VzZW5ldC5IdHRwTWV0aG9kAAAAAAAAAAASAAB4cgAOamF2YS5sYW5nLkVudW0AAAAAAAAAABIAAHhwdAAEUE9TVHNxAH4ABn5xAH4ACXQAA1BVVHNxAH4ABn5xAH4ACXQABkRFTEVURXNyADlvcmcuYm9lc2VuZXQucHJlZGljYXRlLm9wZXJhdGlvbnMuSHR0cFN0YXR1c0NvZGVQcmVkaWNhdGXVwZSHbFavjgIAAkkAC3N0YXR1c1ZhbHVlTAAPc3RhdHVzT3BlcmF0aW9udABFTG9yZy9ib2VzZW5ldC9wcmVkaWNhdGUvb3BlcmF0aW9ucy9IdHRwU3RhdHVzQ29kZVByZWRpY2F0ZSRPUEVSQVRJT047eHAAAAGUfnIAQ29yZy5ib2VzZW5ldC5wcmVkaWNhdGUub3BlcmF0aW9ucy5IdHRwU3RhdHVzQ29kZVByZWRpY2F0ZSRPUEVSQVRJT04AAAAAAAAAABIAAHhxAH4ACnQABUVRVUFM";

    @Test
    public void testDeserialize() throws Exception {
        Predicate<FilterableHttpResult> predicate = SerializationUtil.deserializePredicate(serializedPredicate);
        assertNotNull(predicate);

    }

}
